language: r
sudo: required
dist: trusty
cache: packages
r: bioc-devel

r_packages:
  - pkgdown

before_deploy:
  - R CMD INSTALL .
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change
